format = """
[](fg:#a3aed2)\
[ ](fg:#090c0c bg:#a3aed2)\
[](fg:#a3aed2 bg:#5173b8)\
$directory\
[](fg:#5173b8 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260)\
$fill\
$cmd_duration\
$time\n\
$character"""

[directory]
truncation_length = 5
truncation_symbol = "…/"
format = "[   $path ](fg:#e3e5e5 bg:#5173b8)"

[git_branch]
symbol = ""
format = "[ $symbol $branch ](fg:#769ff0 bg:#394260)"

[git_status]
format = "[$all_status$ahead_behind](fg:#769ff0 bg:#394260)"

[fill]
symbol = " "

[time]
disabled = false
time_format = "%T"
format = "[ $time](fg:#a0a9cb) "

[cmd_duration]
min_time = 1000
format = "[󰔟 $duration](fg:#a0a9cb) [](fg:#769ff0) "

[character]
format = " $symbol "
